### ISSUE TITLE
Invadopodia assay

### ISSUE THREAD

**Issue by mcreixell** [meyer-lab/DDMC#483]
@aarmey  I've been trying to find an invadopodia assay similar to the one in figure 3 of [Revach](https://cancerres.aacrjournals.org/content/79/10/2634) et al in PC9 cells, as we discussed, but wasn't able to find anything. Do you think it might be worth asking the authors?

Otherwise, I was wondering whether a different approach, such that figure 7 of [Daria](https://www.pnas.org/content/118/28/e2024596118.abstract) et al could make more sense? Using matrigel/spheroids sounds more standard to me but even so haven't been able to find much on PC9 cells...

**Comment by aarmey** [comment]
Just a note that we talked about this today.
