### ISSUE TITLE
Make DDMC return validated substrates

### ISSUE THREAD

**Issue by mcreixell** [meyer-lab/DDMC#523]
Again, something the reviewers didn't ask for but after spending many hours interpreting DDMC results, I think adding a method within DDMC that returns a list of validated substrates included in a cluster of an upstream kinase could be very helpful. Returning all kinases and phosphatases within each cluster could also be informative. This should be very easy to do. I think I could write this while you review the manuscript or we can just add this after re-submitting @aarmey

**Comment by aarmey** [comment]
Hmm... if you think it would be useful *to you* then I agree. Otherwise, many other things could use your attention.
